### ISSUE TITLE
Allow notification opt-in for users

### ISSUE THREAD

**Issue by ryankortbeek** [AlbertaSat/ex2_ground_station_website#22]
### Brief Feature Description
Users should be able to opt-in to slack notifications upon acquisition of the satellite's signal (AOS) (i.e., when the satellite comes into range).

_1.6 As a satellite operator or mission stakeholder, I want to opt-in to be automatically notified on Slack when a pass is being executed, and the status of the script execution after LOS_

### Additional Details
When a user opts in they must be prompted to specify their slack username which will be assumed to be correct (it must be correct in order for the notification service to work). A "slack_username" column should be added to the user table in the database and it should be updated each time a user opts-in (and specifies a new slack username). Additionally, it should not be a required field.

### Priority
Low.

**Comment by ryankortbeek** [comment]
@ahmedsiad its worth noting that if slack notifications seem to be difficult to integrate, we could also consider email notifications.

**Comment by ryankortbeek** [comment]
When user toggles to opt-in, open a pop up displaying the slack name that is currently stored in the database for that user. Prevent them from confirming opt-in if they have not specified a slack name. Update values stored in the database after confirmation.

**Comment by ahmedsiad** [comment]
Possibly in the future expand the popup window to allow for a range of notification settings such as future passover data, what times to send notifs, etc.
