### ISSUE TITLE
Add forgot password functionality

### ISSUE THREAD

**Issue by ryankortbeek** [AlbertaSat/ex2_ground_station_website#33]
### Brief Feature Description
Allow an existing user to reset their password.

### Priority
Low

**Comment by ahmedsiad** [comment]
There is now a PATCH method request in `user.py` that you can make to modify the user through an API call. The method uses the `UserPatchValidator` in `validators.py` which does not have any required fields, but it would be a good idea to make the usernames of the user a required field. This would require a change to the slack notifications PATCH request in `Home.jsx`.

**Comment by jmmabanta** [comment]
Finished by merging #99 (allows already logged-in users to change their password).
After #90 is finished (with the [database relation refactor](https://github.com/AlbertaSat/ex2_ground_station_website/pull/90#discussion_r904234254)), we can add a 'Manage Users' page available only to admins where they can change the password of the (normal non-admin) users they have created just in case someone forgets
