### ISSUE TITLE
Expose a regularity field in the flight schedules UI

### ISSUE THREAD

**Issue by ryankortbeek** [AlbertaSat/ex2_ground_station_website#34]
### Brief Feature Description
Allow users to specify a regularity for flight schedule commands. This regularity corresponds to how often the flight schedule commands run on the satellite.

### Additional Details
BEFORE starting this task, communicate with the software team to ensure that the functionality is supported by the on board computer of the satellite.

The unit of time that the regularity is expressed in should be further refined with the software team, however, a good starting point may be seconds?

While this is being implemented, the orbital operations team should be consulted regarding the flight schedules workflow.

### Priority
Low

**Comment by jmmabanta** [comment]
Related to my ongoing task of implementing flight schedule upload in comm.py

**Comment by jmmabanta** [comment]
Completed in `fs_upload` branch. Will be pulled in alongside #46
