### ISSUE TITLE
Figure out how to detect AOS

### ISSUE THREAD

**Issue by ryankortbeek** [AlbertaSat/ex2_ground_station_website#40]
### Brief Feature Description
- [x] Determine how acquisition of the satellite's signal (AOS) can be detected so that commands can be sent and users can be notified of a passover.
- [x] Create a wiki page explaining how [automation.py](https://github.com/AlbertaSat/ex2_ground_station_website/blob/master/automation.py) calculates passover frequency, etc.

### Priority
High

**Comment by jmmabanta** [comment]
Just need to add the wiki page explaining how passovers are calculated

**Comment by ahmedsiad** [comment]
Oh I actually did that already, just added another paragraph explaining how I used Pyorbital and included a link to the function in the library for anyone who wants to know the crazy math behind it :)

**Comment by jmmabanta** [comment]
Oh sorry I didn't see that. Great work!
