### ISSUE TITLE
Test comm.py integration with ground station software

### ISSUE THREAD

**Issue by ryankortbeek** [AlbertaSat/ex2_ground_station_website#41]
### Brief Feature Description
Verify that the integration between [comm.py](https://github.com/AlbertaSat/ex2_ground_station_website/blob/master/comm.py) and [ex2_ground_station_software](https://github.com/AlbertaSat/ex2_ground_station_software) is working and behaves as expected. It would be ideal if this could be tested in a realistic environment on the ground station computer when it is set up the way it would be when the satellite is in orbit (i.e., connected to the UHF, able to transmit signals, etc.).

### Additional Details
Follow the instructions listed on the [running the satellite simulator wiki page](https://github.com/AlbertaSat/ex2_ground_station_website/wiki/Running-the-satellite-simulator) but when spinning up the comm.py module, enter anything but `Y` or `y` when prompted if you want to connect to the simulator. You also won't need to run the satellite simulator module. This will cause the comm.py module to attempt to send the communications to the satellite via ex2_ground_station_software and libcsp thus mimicking the setup when the satellite in is orbit.

It will likely be easiest to test this integration if you have followed the manual installation steps as described in [INSTALL.md](https://github.com/AlbertaSat/ex2_ground_station_website/blob/master/INSTALL.md). You should change directories into both submodules that exist in this repo ([libcsp](https://github.com/libcsp/libcsp/tree/master) and [ex2_ground_station_software](https://github.com/AlbertaSat/ex2_ground_station_software)) and install both as described in the repositories that they correspond to.

### Priority
High

**Comment by jmmabanta** [comment]
- [ ]  **TODO:** Write unit tests for gs_software integration in [`groundstation/tests/test_groundstation.py`](https://github.com/AlbertaSat/ex2_ground_station_website/blob/master/groundstation/tests/test_groundstation.py)
    - Could mimic the same tests found in [`ex2_ground_station_software/test`](https://github.com/AlbertaSat/ex2_ground_station_software/tree/master/test)
    - Ensure that tests also work without hardware so that GitHub actions can properly run them.
