### ISSUE TITLE
Implement support for automated command sequences

### ISSUE THREAD

**Issue by ryankortbeek** [AlbertaSat/ex2_ground_station_website#53]
### Brief Feature Description
Support automated command sequences that are run each pass upon AOS. 

### Additional Details
This should be exposed as a new tab within the web app (title = Automated Command Sequence) and present admin users with some sort of UI element that displays the current automated command sequence (empty UI element if none exist). Users should be able to add, remove, and rearrange commands.

One idea is a text box with commands separated by newline. When the user clicks a save button the corresponding table in the database is updated.

Could store these commands in a separate table within the database and then create communications objects out of them on AOS.

**Only admin users** should have access to this file.

### Priority
High

**Comment by ryankortbeek** [comment]
As per discussion with @joshdellaz  this functionality will not be exposed via the web app and will remain supported through the text file [automation.txt](https://github.com/AlbertaSat/ex2_ground_station_website/blob/master/automation.txt) that lives on the ground station computer and contains commands separated by newlines. Commands in this file will be executed upon AOS. More info can be found on the [wiki](https://github.com/AlbertaSat/ex2_ground_station_website/wiki/The-comm.py-Module#automationpy). Closing this issue for now.

**Comment by jmmabanta** [comment]
I vaguely remember us talking about the automation of commands being sent on AOS in our Saturday meeting a few weeks ago. I thought we needed to keep it strictly to the text file due to security, but I guess if the website will only be used locally on the ground station computer then it shouldn't be a problem.

**Comment by ryankortbeek** [comment]
> I vaguely remember us talking about the automation of commands being sent on AOS in our Saturday meeting a few weeks ago. I thought we needed to keep it strictly to the text file due to security, but I guess if the website will only be used locally on the ground station computer then it shouldn't be a problem.

I think its important to build the web app in a way that will allow it to be used by anyone with an account (only admins can add new non-admin accounts and admins can only be created by us via database) - not just locally on the gs computer. Then only expose certain potentially dangerous features to admin users. Good practice security wise. More discussion needs to happen around how we deploy the web app but for now we should continue to implement features with this assumption and re-visit existing features accordingly.

**Comment by ryankortbeek** [comment]
> I don't see a difference (functionally) between "queuing of commands to be executed on the next AOS (or immediately if the satellite is currently passing over)" and "a text file containing newline separated commands that is read from and executed each AOS." Do they not achieve the same result?

Not necessarily, the text file containing newline separated commands would be executed automatically upon every AOS whereas the queueing of commands is manual and if you want certain commands to be run on each AOS you would have to go queue the commands beforehand each time

**Comment by joshdellaz** [comment]
I see. So the text file method is basically just a time-saver. In that case, it's worth doing so long as the development time isn't anything crazy.
